version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - frontend-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  frontend-network:
    driver: bridge
    name: urban-services-frontend-network